### ISSUE TITLE
There are two README files

### ISSUE THREAD

**Issue by eblume** [phildini/thanks#17]
You've currently got two README files in the project's root directory. Probably not intentional? Note also the interaction with MANIFEST.in, which currently ignores README.md - maybe that's intentional?

**Comment by eblume** [comment]
Correction - README.md _is_ included by the recursive-include in MANIFEST.in

**Comment by phildini** [comment]
This is more because github expects one thing and PyPI expects another thing. Consolidating those into an RST is probably a good idea.

**Comment by tomdottom** [comment]
I thought github would accept either a `README.md` or `README.rst` as long as there is just on of the two. Also doesn't PyPI now accept `README.md`?

I guess the question is "which do we prefer?"

**Comment by phildini** [comment]
When I started this repo, github hadn't yet added the .rst support.... I'm fine killing the .md one and using just RST, since it's more python-ecosystem friendly.
